In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3],dtype="i")

In [6]:
a

array([1, 2, 3], dtype=int32)

In [7]:
b = np.array([[1,2,3],[4,5,6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [12]:
b.dtype

dtype('int32')

In [15]:
b.itemsize

4

In [17]:
b.nbytes

24

In [18]:
b.size

6

# Accessing/Changing specific elements, rows, columns, etc

In [20]:
a = np.array([[1,2,3,4,5,6],[11,12,13,14,15,16]])

In [21]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [25]:
a[1,2:4]

array([13, 14])

In [31]:
a[0,2]

3

In [34]:
a[:,3]

array([ 4, 14])

In [40]:
a[0,::2]

array([1, 3, 5])

In [51]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [52]:
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [53]:
b.ndim

3

In [55]:
b[0,1,-1]

6

In [56]:
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [57]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16]])

In [59]:
a[1,2] = 10

In [60]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 10, 14, 15, 16]])

# Initializing Different Types of Arrays

In [62]:
np.zeros((2,3),dtype="i")

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [65]:
np.ones((4,3),dtype="i")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [66]:
np.full((2,2),55)

array([[55, 55],
       [55, 55]])

In [68]:
np.random.randint(10,55,size=(2,4))

array([[31, 14, 44, 29],
       [43, 45, 51, 14]])

In [69]:
np.random.rand(2,3)

array([[0.05351457, 0.06503627, 0.01777657],
       [0.69072514, 0.01517439, 0.28665403]])

In [72]:
np.identity(3,dtype="i")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [77]:
a1 = np.array([[1,2,3]])

In [120]:
z = np.repeat(a1,4,axis=0)

# Maths

In [79]:
c = np.array([5,6,7,8])

In [80]:
c

array([5, 6, 7, 8])

In [81]:
c + 2

array([ 7,  8,  9, 10])

In [82]:
c - 4

array([1, 2, 3, 4])

In [83]:
c * 2

array([10, 12, 14, 16])

In [84]:
c // 2

array([2, 3, 3, 4], dtype=int32)

In [85]:
c **4

array([ 625, 1296, 2401, 4096], dtype=int32)

In [86]:
pow(c,5)

array([ 3125,  7776, 16807, 32768], dtype=int32)

In [88]:
np.cos(c)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

In [89]:
np.sin(c)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [90]:
np.tan(c)

array([-3.38051501, -0.29100619,  0.87144798, -6.79971146])

In [91]:
d = np.array([1,2,3,4])

In [92]:
c+d

array([ 6,  8, 10, 12])

In [93]:
c - d

array([4, 4, 4, 4])

In [95]:
d ** c

array([    1,    64,  2187, 65536])

In [99]:
c * d

array([ 5, 12, 21, 32])

# Linear Algebra

In [97]:
np.matmul(c,d)

70

In [108]:
a1 = np.array([[4,5,6],[7,8,9]])
a2 = np.array([[11,12],[13,15],[16,17]])
a1.shape , a2.shape

((2, 3), (3, 2))

In [109]:
np.matmul(a1,a2)

array([[205, 225],
       [325, 357]])

# Statistics

In [111]:
c

array([5, 6, 7, 8])

In [112]:
np.min(c)

5

In [113]:
np.max(c)

8

In [116]:
np.sum(c)

26

In [117]:
np.average(c)

6.5

In [118]:
c.mean()

6.5

# Reorganizing Arrays

In [121]:
z

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9]])

In [123]:
z.shape

(8, 3)

In [124]:
z.reshape(3,8)

array([[4, 5, 6, 4, 5, 6, 4, 5],
       [6, 4, 5, 6, 7, 8, 9, 7],
       [8, 9, 7, 8, 9, 7, 8, 9]])

In [126]:
np.hstack(z)

array([4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7,
       8, 9])

# Miscellaneous

In [127]:
data = np.genfromtxt('data.txt',delimiter=",")

In [130]:
data = data.astype('int32')

In [131]:
data.dtype

dtype('int32')

In [132]:
data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [134]:
data.size

54

In [136]:
data.ndim

2

In [137]:
data[]

array([  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
         6,   7,   0,  11,  12])